name: mrg app CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

   

jobs:
    react-app-workflow:
        runs-on: ubuntu-latest 
        environment: Production 
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js 20.x
              uses: actions/setup-node@v2
              with:
                  node-version: 20.x                   
            - name: npm ci
              run: npm ci
            - name: format
              run: npm run prettier
            - name: lint
              run: npm run lint
            - name: build
              run: npm run build --if-present
