name: mrg app CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    react-app-workflow:     
        runs-on: ubuntu-latest  
        environment: 
              name: Production
        steps:
            - name: Make envfile
              uses: SpicyPizza/create-envfile@v2.0
              with: 
                  envkey_NEXT_STRAPI_URL_API_ENDPOINT: ${{ secrets.NEXT_STRAPI_URL_API_ENDPOINT }}
                  envkey_NEXT_STRAPI_URL: ${{ secrets.NEXT_STRAPI_URL }}
                  envkey_NEXT_API_TOKEN: ${{ secrets.NEXT_API_TOKEN }}
            - uses: actions/checkout@v2
            - name: Use Node.js 20.x
              uses: actions/setup-node@v2
              with:
                  node-version: 20.x
            - name: npm ci
              run: npm ci
            - name: format
              run: npm run prettier
            - name: lint
              run: npm run lint
            - name: build
              run: npm run build --if-present
